#!/bin/bash
echo "🏛️ IMPERIAL STACK REVIVAL PROTOCOL v2.0"
echo "======================================="
echo "Timestamp: $(date '+%Y-%m-%d %H:%M:%S')"
echo "IDC Status: Enquiry #4000120009 (SENTC)"
echo ""

# 1. DIAGNOSTIC SCAN
echo "🔍 RUNNING DIAGNOSTIC SCAN..."
echo "----------------------------"

# Check current status
check_port() {
    if nc -z localhost $1 2>/dev/null; then
        echo "✅ Port $1: ACTIVE"
        return 0
    else
        echo "❌ Port $1: INACTIVE"
        return 1
    fi
}

echo "Checking critical ports:"
check_port 8088  # Executive Dashboard
check_port 1880  # Node-RED Automation
check_port 11434 # Ollama Intelligence (default)

# Check processes
echo ""
echo "🧠 PROCESS STATUS:"
if pgrep -f "python3.*http.server" > /dev/null; then
    echo "✅ Python HTTP Server: ACTIVE"
else
    echo "❌ Python HTTP Server: INACTIVE"
fi

if pgrep -f "node-red" > /dev/null; then
    echo "✅ Node-RED: ACTIVE"
else
    echo "❌ Node-RED: INACTIVE"
fi

if pgrep -f "ollama" > /dev/null; then
    echo "✅ Ollama: ACTIVE"
else
    echo "❌ Ollama: INACTIVE"
fi

if pgrep -f "cloudflared" > /dev/null; then
    echo "✅ Cloudflare Tunnel: ACTIVE"
else
    echo "❌ Cloudflare Tunnel: INACTIVE"
fi

# 2. TARGETED REVIVAL
echo ""
echo "🚀 INITIATING TARGETED REVIVAL..."
echo "--------------------------------"

# Kill only what's necessary
if ! check_port 8088; then
    echo "🔄 Reviving Executive Dashboard..."
    pkill -f "python3.*http.server"
    cd ~/humbu_community_nexus
    nohup python3 -m http.server 8088 > ~/logs/dashboard_revive.log 2>&1 &
    sleep 2
    check_port 8088
fi

if ! check_port 1880; then
    echo "🔄 Reviving Node-RED Automation..."
    pkill -f "node-red"
    nohup node-red > ~/logs/node-red_revive.log 2>&1 &
    sleep 3
    check_port 1880
fi

if ! pgrep -f "ollama" > /dev/null; then
    echo "🔄 Reviving Ollama Intelligence..."
    pkill -f "ollama"
    nohup ollama serve > ~/logs/ollama_revive.log 2>&1 &
    sleep 5
    if pgrep -f "ollama" > /dev/null; then
        echo "✅ Ollama: REVIVED"
    else
        echo "⚠️ Ollama may need manual start: ollama serve"
    fi
fi

if ! pgrep -f "cloudflared" > /dev/null; then
    echo "🔄 Reviving Public Bridge..."
    pkill -f "cloudflared"
    sleep 2
    nohup cloudflared tunnel run --url http://localhost:8088 humbu-imperial > ~/logs/tunnel_revive.log 2>&1 &
    sleep 3
    if pgrep -f "cloudflared" > /dev/null; then
        echo "✅ Cloudflare Tunnel: REVIVED"
        echo "🌐 Public URL: monitor.humbu.store"
    else
        echo "⚠️ Cloudflare Tunnel may need token refresh"
    fi
fi

# 3. POST-REVIVAL VERIFICATION
echo ""
echo "✅ REVIVAL COMPLETE - RUNNING VERIFICATION..."
echo "--------------------------------------------"

# Generate status report
STATUS_REPORT="$HOME/humbu_community_nexus/revival_status_$(date +%Y%m%d_%H%M%S).txt"
cat << REPORT > $STATUS_REPORT
IMPERIAL STACK REVIVAL REPORT
=============================
Timestamp: $(date '+%Y-%m-%d %H:%M:%S')
IDC Enquiry: #4000120009

COMPONENT STATUS:
• Executive Dashboard (8088): $(check_port 8088 > /dev/null && echo "ACTIVE" || echo "INACTIVE")
• Node-RED Automation (1880): $(check_port 1880 > /dev/null && echo "ACTIVE" || echo "INACTIVE")
• Ollama Intelligence: $(pgrep -f ollama > /dev/null && echo "ACTIVE" || echo "INACTIVE")
• Cloudflare Tunnel: $(pgrep -f cloudflared > /dev/null && echo "ACTIVE" || echo "INACTIVE")

ACCESS POINTS:
• Local Dashboard: http://localhost:8088
• Public Dashboard: monitor.humbu.store
• Automation Interface: http://localhost:1880
• Intelligence API: http://localhost:11434

CRITICAL FILES:
• Industrial Data: ~/humbu_community_nexus/gauteng_industrial.json
• Financial Ledger: ~/humbu_community_nexus/financial_ledger.json
• Sage Insights: ~/humbu_community_nexus/sage_insights_$(date +%Y%m%d).txt
• Monday Briefing: ~/humbu_community_nexus/monday_briefing_*.txt

RECOMMENDED ACTIONS:
1. Verify all URLs above are accessible
2. Send status update to IDC if during presentation
3. Run 'system-heartbeat' for full diagnostic
4. Test 'nexus-revive' command in another terminal

--- 
Generated by Imperial Revival Protocol v2.0
REPORT

echo "📄 Status report saved: $STATUS_REPORT"

# 4. FINAL SYSTEM CHECK
echo ""
echo "🏁 FINAL SYSTEM STATUS:"
echo "----------------------"
if check_port 8088 && check_port 1880 && pgrep -f "ollama" > /dev/null && pgrep -f "cloudflared" > /dev/null; then
    echo "🎉 IMPERIAL STACK: 100% OPERATIONAL"
    echo ""
    echo "💼 READY FOR IDC PRESENTATION:"
    echo "• Public Dashboard: monitor.humbu.store"
    echo "• Local Backup: http://localhost:8088"
    echo "• Automation: http://localhost:1880"
    echo "• Intelligence: Ollama serving"
    echo ""
    echo "🚀 NEXT STEP: Open dashboard in browser and present"
else
    echo "⚠️  IMPERIAL STACK: PARTIALLY OPERATIONAL"
    echo ""
    echo "🔧 REQUIRED ACTIONS:"
    echo "1. Check individual logs in ~/logs/"
    echo "2. Run manual starts for failed components"
    echo "3. Use 'system-heartbeat' for detailed diagnostics"
    echo "4. Contact technical support if issues persist"
fi

echo ""
echo "🛡️ REVIVAL PROTOCOL COMPLETE"
