#! /usr/bin/env python3
print("==================================================")
print("       HUMBU IMPERIAL: VILLAGE INTELLIGENCE")
print("          VILLAGE: THOHOYANDOU HUB")
print("          DATE: 2026-01-01")
print("==================================================")
print("📊 DEMAND LEVEL: HIGH (Retail & Agri)")
print("🛣️ ROAD STATUS: ACCESSIBLE (No blockages)")
print("⛽ FUEL AVAILABILITY: 100% (Last-mile ready)")
print("🛒 TOP 3 PRODUCTS IN DEMAND:")
print("   1. Maize Meal (5kg/10kg)")
print("   2. Poultry Feed")
print("   3. Cooking Oil")
print("--------------------------------------------------")
print("💡 ADVISORY: Redirect 20% Gauteng stock to this node.")
print("✅ SAVINGS ESTIMATE: R2,400 (Avoided stockout)")
print("==================================================")
