#! /usr/bin/env python3
print("==================================================")
print("       HUMBU IMPERIAL: VILLAGE INTELLIGENCE")
print("          VILLAGE: SIBASA JUNCTION")
print("          DATE: 2026-01-01")
print("==================================================")
print("📊 DEMAND LEVEL: MEDIUM (Logistics Heavy)")
print("🛣️ ROAD STATUS: CAUTION (Heavy Rain/Congestion)")
print("⛽ FUEL AVAILABILITY: 85% (Queueing detected)")
print("🛒 TOP 3 PRODUCTS IN DEMAND:")
print("   1. Bottled Water")
print("   2. Cement (Construction surge)")
print("   3. Perishables (Fresh produce)")
print("--------------------------------------------------")
print("💡 ADVISORY: Delay non-essential delivery by 6 hrs.")
print("✅ SAVINGS ESTIMATE: R1,200 (Fuel/Idling cost)")
print("==================================================")
