#!/bin/bash
echo "🚨 URGENT: MOBILE MONEY LINKING CAMPAIGN"
echo "Target: Increase from 5.8% to 100% in 30 days"
echo ""
echo "DAILY TARGETS:"
echo "Day 1-7: 50 users (7 per day)"
echo "Day 8-14: 80 users (11 per day)"
echo "Day 15-21: 80 users (11 per day)"
echo "Day 22-30: 80 users (9 per day)"
echo ""
echo "METHOD:"
echo "1. Village meetings (15 villages)"
echo "2. Market day promotions"
echo "3. Church/School partnerships"
echo "4. Champion home visits"
echo ""
echo "INCENTIVES:"
echo "• First 50 users: R20 airtime"
echo "• Champions: R300/month + smartphone"
echo "• 100% villages: R2000 project fund"
